SELECT 
    P.PRODUCT_ID,
    MAX(CASE WHEN GI.GOOD_IDENTIFICATION_TYPE_ID = 'ERP_ID' THEN GI.ID_VALUE END) AS ERP_ID,
    MAX(CASE WHEN GI.GOOD_IDENTIFICATION_TYPE_ID = 'SKU' THEN GI.ID_VALUE END) AS HOTWAX_ID_SKU,
    MAX(CASE WHEN GI.GOOD_IDENTIFICATION_TYPE_ID = 'SHOPIFY_PROD_ID' THEN GI.ID_VALUE END) AS SHOPIFY_PRODUCT_ID
FROM 
    product P
JOIN 
    good_identification GI 
    ON P.PRODUCT_ID = GI.PRODUCT_ID
WHERE 
    GI.GOOD_IDENTIFICATION_TYPE_ID IN ('ERP_ID', 'SHOPIFY_PROD_ID','SKU')
GROUP BY 
    P.PRODUCT_ID;
